# react-app/nginx.conf
server {
    listen 80;

    # Serve React static files
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;  # needed for React Router
    }

    # Proxy API calls to Flask service by Kubernetes DNS name
    location /api/ {
        proxy_pass http://visual-dictionary:5000;
        proxy_set_header Host $host;
    }
}